language: erlang
script: "./travis-ci"
before_install:
    - sudo add-apt-repository -y ppa:motiejus/piqi
    - sudo apt-get update -qq
    - sudo apt-get install piqi
otp_release:
   - R15B03
   - R15B02
   - R15B02
   - R15B01
