language: erlang
script: "make all test"
before_install:
    - sudo add-apt-repository -y ppa:motiejus/piqi
    - sudo apt-get update -qq
    - sudo apt-get install rebar piqi
otp_release:
   - R16B
   - R15B03
   - R15B02
   - R15B02
   - R15B01
   - R15B
   - R14B04
   - R14B03
   - R14B02
