#!/bin/sh
set -xe

rebar get-deps compile generate
rebar skip_deps=true eunit

./rel/erl_piqibench/bin/erl_piqibench start
sleep 2
./rel/erl_piqibench/bin/erl_piqibench ping

RET=$(curl -H 'Content-Type: application/json' \
    --data '{"a":1,"b":1}' \
    http://127.0.0.1:8090/piqibench/get) || true

./rel/erl_piqibench/bin/erl_piqibench stop

test "$RET" = '{ "sum": 3 }'
